# Site settings
title: Furkan Polat
description: Information Technology Specialist
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g.

last_build: [21.11.2025]